Controllers/InvoiceChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InvoiceTestApp.Data;
using InvoiceTestApp.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace InvoiceTestApp.Controllers
{
    public class InvoiceChartController : Controller
    {
        private readonly IInvoiceRepository _repository;

        public InvoiceChartController(IInvoiceRepository repository)
        {
            _repository = repository;
        }
        // GET: InvoiceChartController1
        public ActionResult Index()
        {
            return View();
        }


        //POST: InvoiceChartController1/Create
        //[HttpPost]
        //public ActionResult GetAmounts(string year, string month)
        //{
        //var yearInt = Convert.ToInt32(year);
        //var monthInt = Convert.ToInt32(month);
        //var lastDayOfMonth = DateTime.DaysInMonth(yearInt, monthInt);
        //var charges = _repository.GetCharges();

        //var beginDate = new DateTime(yearInt, monthInt, 1);
        //var endDate = new DateTime(yearInt, monthInt, lastDayOfMonth);

        //decimal amountDay = 0;
        //decimal amountNight = 0;
        //decimal amountWeekend = 0;

        //foreach (var charge in charges)
        //{
        //    if (charge.ChargeName == "Day")
        //    {
        //        amountDay = _repository.GetAmountFromProcedure(beginDate, endDate, charge.Id);
        //    }

        //    if (charge.ChargeName == "Night")
        //    {
        //        amountNight = _repository.GetAmountFromProcedure(beginDate, endDate, charge.Id);
        //    }

        //    if (charge.ChargeName == "Weekend")
        //    {
        //        amountWeekend = _repository.GetAmountFromProcedure(beginDate, endDate, charge.Id);
        //    }
        //}

        //var model = new GetAmountPerChargeVM();
        //model.AmountDay = amountDay;
        //model.AmountNight = amountNight;
        //model.AmountWeekend = amountWeekend;

        //    return View(model)
        //}
    }   
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InvoiceTestApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="preload" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" data-rocket-async="style" as="style" onload="this.onload=null;this.rel='stylesheet'" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InvoiceTestApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Invoices</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="InvoiceChart" asp-action="Index">Invoice Chart</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - InvoiceTestApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>